# Generated by Django 6.0.2 on 2026-02-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppleDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('device_type', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('storage_gb', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('DAMAGED', 'Damaged'), ('ACTIVE', 'Active'), ('FOR_SALE', 'For Sale'), ('SOLD', 'Sold'), ('PERSONAL', 'Personal Collection')], default='ACTIVE', max_length=20)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.appledevice')),
            ],
        ),
    ]
