# Generated by Django 6.0.2 on 2026-02-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appledevice',
            name='model',
            field=models.TextField(blank=True, null=True),
        ),
    ]
