# Generated by Django 6.0.2 on 2026-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_appledevice_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appledevice',
            name='image_url',
        ),
        migrations.AddField(
            model_name='appledevice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/'),
        ),
        migrations.AlterField(
            model_name='appledevice',
            name='model',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
